cache:
  paths:
    - node_modules/

stages:
  - setup
  - test

setup:
  stage: setup
  image: node:12.16.1
  script:
    - npm install

e2e:chrome:
  stage: test
  image: cypress/browsers:node12.14.1-chrome85-ff81
  script:
    - npm install
    - npm install cypress
    - npm run test:chrome

e2e:firefox:
  stage: test
  image: cypress/browsers:node12.14.1-chrome85-ff81
  script:
    - npm install
    - npm install cypress
    - npm run test:firefox

